// ============================================================
// Mock Data — realistic demo data for 30+ contacts
// Used when DEMO_MODE=true or Coral APIs aren't connected
// ============================================================

import type { Contact, GmailThread, CalendarEvent, NetworkStats, LinkedInSignal } from './types'

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

export const mockContacts: Contact[] = [
  {
    page_id: 'c001', name: 'Geetansh Vikram', email: 'sarah.chen@stripe.com',
    company: 'Stripe', role: 'VP of Engineering', github_username: 'Geetansh-12', tags: ['mentor', 'tech'],
    relationship: 'close', notes: 'Met at StrangeLoop 2023. Great systems thinker. Offered to review my architecture doc.',
    last_contact_at: daysAgo(3), days_since_contact: 3, health_score: 92,
    last_email_received: daysAgo(3), total_emails_received: 24, total_emails_sent: 18,
    last_meeting: daysAgo(7), total_meetings: 8,
    last_slack: daysAgo(5), total_slack_messages: 45,
    last_twitter_interaction: daysAgo(12), twitter_interactions: 6,
    last_linkedin_signal: daysAgo(15), linkedin_recent_signals: 'Promoted to VP of Engineering at Stripe',
  },
  {
    page_id: 'c002', name: 'Marcus Rivera', email: 'marcus@linear.so',
    company: 'Linear', role: 'Co-founder & CTO', github_username: 'leerob', tags: ['founder', 'investor-track'],
    relationship: 'professional', notes: 'Brilliant product mind. Wants to collaborate on dev tools.',
    last_contact_at: daysAgo(8), days_since_contact: 8, health_score: 85,
    last_email_received: daysAgo(8), total_emails_received: 12, total_emails_sent: 10,
    last_meeting: daysAgo(14), total_meetings: 5,
    last_slack: daysAgo(10), total_slack_messages: 22,
    last_twitter_interaction: daysAgo(4), twitter_interactions: 15,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c003', name: 'Priya Patel', email: 'priya@anthropic.com',
    company: 'Anthropic', role: 'Research Scientist', github_username: 'rauchg', tags: ['AI', 'research'],
    relationship: 'close', notes: 'Co-authored the alignment paper. Sharp thinker on safety.',
    last_contact_at: daysAgo(2), days_since_contact: 2, health_score: 95,
    last_email_received: daysAgo(2), total_emails_received: 31, total_emails_sent: 28,
    last_meeting: daysAgo(5), total_meetings: 12,
    last_slack: daysAgo(2), total_slack_messages: 89,
    last_twitter_interaction: daysAgo(1), twitter_interactions: 22,
    last_linkedin_signal: daysAgo(30), linkedin_recent_signals: 'Published paper on constitutional AI training methods',
  },
  {
    page_id: 'c004', name: 'Alex Kim', email: 'alex.kim@anthropic.com',
    company: 'Anthropic', role: 'Staff Engineer', github_username: null, tags: ['engineer', 'ex-colleague'],
    relationship: 'close', notes: 'Worked together at Google for 2 years. Great debugging partner.',
    last_contact_at: daysAgo(12), days_since_contact: 12, health_score: 78,
    last_email_received: daysAgo(12), total_emails_received: 18, total_emails_sent: 15,
    last_meeting: daysAgo(20), total_meetings: 6,
    last_slack: daysAgo(15), total_slack_messages: 34,
    last_twitter_interaction: daysAgo(8), twitter_interactions: 9,
    last_linkedin_signal: daysAgo(3), linkedin_recent_signals: 'Joined Anthropic as Staff Engineer | Previously at Google',
  },
  {
    page_id: 'c005', name: 'Jordan Taylor', email: 'jordan@vercel.com',
    company: 'Vercel', role: 'Head of Developer Relations', github_username: null, tags: ['devrel', 'speaker'],
    relationship: 'professional', notes: 'Amazing speaker. Connected us to the Next.js team.',
    last_contact_at: daysAgo(5), days_since_contact: 5, health_score: 88,
    last_email_received: daysAgo(5), total_emails_received: 15, total_emails_sent: 12,
    last_meeting: daysAgo(10), total_meetings: 7,
    last_slack: daysAgo(6), total_slack_messages: 28,
    last_twitter_interaction: daysAgo(3), twitter_interactions: 18,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c006', name: 'Rachel Kim', email: 'rachel@a16z.com',
    company: 'a16z', role: 'Partner', github_username: null, tags: ['investor', 'advisor'],
    relationship: 'professional', notes: 'Intro-ed us to 3 portfolio companies. Strong in infrastructure.',
    last_contact_at: daysAgo(89), days_since_contact: 89, health_score: 32,
    last_email_received: daysAgo(89), total_emails_received: 8, total_emails_sent: 6,
    last_meeting: daysAgo(95), total_meetings: 3,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(60), twitter_interactions: 4,
    last_linkedin_signal: daysAgo(20), linkedin_recent_signals: 'Led Series B for DevTools startup',
  },
  {
    page_id: 'c007', name: 'David Park', email: 'david.park@notion.so',
    company: 'Notion', role: 'PM Lead', github_username: null, tags: ['product', 'API'],
    relationship: 'professional', notes: 'Discussing API integration partnership. Sharp product sense.',
    last_contact_at: daysAgo(65), days_since_contact: 65, health_score: 38,
    last_email_received: daysAgo(65), total_emails_received: 10, total_emails_sent: 8,
    last_meeting: daysAgo(70), total_meetings: 4,
    last_slack: daysAgo(68), total_slack_messages: 15,
    last_twitter_interaction: null, twitter_interactions: 0,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c008', name: 'Maya Johnson', email: 'maya@figma.com',
    company: 'Figma', role: 'Head of Design Systems', tags: ['design', 'creative'],
    relationship: 'professional', notes: 'Incredible eye for detail. Working on design system standards.',
    last_contact_at: daysAgo(38), days_since_contact: 38, health_score: 52,
    last_email_received: daysAgo(38), total_emails_received: 7, total_emails_sent: 5,
    last_meeting: daysAgo(42), total_meetings: 3,
    last_slack: daysAgo(40), total_slack_messages: 12,
    last_twitter_interaction: daysAgo(20), twitter_interactions: 8,
    last_linkedin_signal: daysAgo(10), linkedin_recent_signals: 'Spoke at Config 2025 about design token architecture',
  },
  {
    page_id: 'c009', name: 'James Liu', email: 'james.liu@google.com',
    company: 'Google', role: 'Staff Software Engineer', tags: ['engineer', 'infra'],
    relationship: 'close', notes: 'Go-to person for distributed systems questions. Coffee buddy.',
    last_contact_at: daysAgo(45), days_since_contact: 45, health_score: 48,
    last_email_received: daysAgo(45), total_emails_received: 14, total_emails_sent: 12,
    last_meeting: daysAgo(50), total_meetings: 9,
    last_slack: daysAgo(47), total_slack_messages: 56,
    last_twitter_interaction: null, twitter_interactions: 0,
    last_linkedin_signal: daysAgo(5), linkedin_recent_signals: 'Promoted to Staff Software Engineer',
  },
  {
    page_id: 'c010', name: 'Nadia Hassan', email: 'nadia@spotify.com',
    company: 'Figma', role: 'VP of Product', tags: ['product', 'leader'],
    relationship: 'acquaintance', notes: 'Met at a dinner party. Interesting perspective on creator tools.',
    last_contact_at: daysAgo(120), days_since_contact: 120, health_score: 18,
    last_email_received: daysAgo(120), total_emails_received: 3, total_emails_sent: 2,
    last_meeting: daysAgo(130), total_meetings: 1,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(90), twitter_interactions: 2,
    last_linkedin_signal: daysAgo(7), linkedin_recent_signals: 'Joined Figma as VP of Product | Previously at Spotify',
  },
  {
    page_id: 'c011', name: 'Tom Chen', email: 'tom@stealth.ai',
    company: 'Stealth Startup', role: 'Founder & CEO', tags: ['founder', 'AI'],
    relationship: 'close', notes: 'Left Meta to start something. Very secretive but brilliant.',
    last_contact_at: daysAgo(18), days_since_contact: 18, health_score: 72,
    last_email_received: daysAgo(18), total_emails_received: 20, total_emails_sent: 17,
    last_meeting: daysAgo(25), total_meetings: 6,
    last_slack: daysAgo(20), total_slack_messages: 38,
    last_twitter_interaction: daysAgo(14), twitter_interactions: 5,
    last_linkedin_signal: daysAgo(28), linkedin_recent_signals: 'Founded stealth AI startup | Left Meta',
  },
  {
    page_id: 'c012', name: 'Luis Garcia', email: 'luis@vercel.com',
    company: 'Vercel', role: 'Principal Engineer', tags: ['engineer', 'open-source'],
    relationship: 'professional', notes: 'Core contributor to Next.js. Helped debug our SSR issues.',
    last_contact_at: daysAgo(6), days_since_contact: 6, health_score: 82,
    last_email_received: daysAgo(10), total_emails_received: 9, total_emails_sent: 7,
    last_meeting: daysAgo(6), total_meetings: 4,
    last_slack: daysAgo(8), total_slack_messages: 20,
    last_twitter_interaction: daysAgo(2), twitter_interactions: 12,
    last_linkedin_signal: daysAgo(14), linkedin_recent_signals: 'Promoted to Principal Engineer at Vercel',
  },
  {
    page_id: 'c013', name: 'Emily Zhang', email: 'emily.zhang@openai.com',
    company: 'OpenAI', role: 'Product Manager', tags: ['AI', 'product'],
    relationship: 'professional', notes: 'Smart PM. Working on API developer experience.',
    last_contact_at: daysAgo(22), days_since_contact: 22, health_score: 65,
    last_email_received: daysAgo(22), total_emails_received: 8, total_emails_sent: 6,
    last_meeting: daysAgo(30), total_meetings: 3,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(15), twitter_interactions: 7,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c014', name: 'Sophie Martin', email: 'sophie@retool.com',
    company: 'Retool', role: 'Engineering Manager', tags: ['engineer', 'manager'],
    relationship: 'close', notes: 'Great leadership mentor. Helped me think through team scaling.',
    last_contact_at: daysAgo(15), days_since_contact: 15, health_score: 76,
    last_email_received: daysAgo(15), total_emails_received: 16, total_emails_sent: 14,
    last_meeting: daysAgo(21), total_meetings: 5,
    last_slack: daysAgo(17), total_slack_messages: 30,
    last_twitter_interaction: daysAgo(10), twitter_interactions: 4,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c015', name: 'Ryan O\'Brien', email: 'ryan@datadog.com',
    company: 'Datadog', role: 'Senior Engineer', tags: ['observability', 'infra'],
    relationship: 'acquaintance', notes: 'Met at KubeCon. Good insights on observability patterns.',
    last_contact_at: daysAgo(95), days_since_contact: 95, health_score: 22,
    last_email_received: daysAgo(95), total_emails_received: 4, total_emails_sent: 3,
    last_meeting: daysAgo(100), total_meetings: 2,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(80), twitter_interactions: 3,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c016', name: 'Aisha Williams', email: 'aisha@hashicorp.com',
    company: 'HashiCorp', role: 'Developer Advocate', tags: ['devrel', 'cloud'],
    relationship: 'professional', notes: 'Co-presented at HashiConf. Excellent communicator.',
    last_contact_at: daysAgo(42), days_since_contact: 42, health_score: 45,
    last_email_received: daysAgo(42), total_emails_received: 6, total_emails_sent: 5,
    last_meeting: daysAgo(55), total_meetings: 2,
    last_slack: daysAgo(48), total_slack_messages: 10,
    last_twitter_interaction: daysAgo(30), twitter_interactions: 8,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c017', name: 'Chris Anderson', email: 'chris@netlify.com',
    company: 'Netlify', role: 'CTO', tags: ['executive', 'jamstack'],
    relationship: 'professional', notes: 'Fascinating takes on edge computing and serverless.',
    last_contact_at: daysAgo(55), days_since_contact: 55, health_score: 40,
    last_email_received: daysAgo(55), total_emails_received: 5, total_emails_sent: 4,
    last_meeting: daysAgo(60), total_meetings: 2,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(35), twitter_interactions: 6,
    last_linkedin_signal: daysAgo(45), linkedin_recent_signals: 'Published article on edge-first architecture',
  },
  {
    page_id: 'c018', name: 'Zoe Nakamura', email: 'zoe@github.com',
    company: 'GitHub', role: 'Senior PM', tags: ['product', 'developer-tools'],
    relationship: 'close', notes: 'Running Copilot for Enterprise. Deeply thoughtful about DX.',
    last_contact_at: daysAgo(9), days_since_contact: 9, health_score: 84,
    last_email_received: daysAgo(9), total_emails_received: 19, total_emails_sent: 16,
    last_meeting: daysAgo(14), total_meetings: 7,
    last_slack: daysAgo(11), total_slack_messages: 42,
    last_twitter_interaction: daysAgo(6), twitter_interactions: 11,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c019', name: 'Dan Abramov', email: 'dan@bluesky.com',
    company: 'Bluesky', role: 'Engineer', tags: ['react', 'open-source', 'legend'],
    relationship: 'acquaintance', notes: 'Had a great conversation about React Server Components future.',
    last_contact_at: daysAgo(75), days_since_contact: 75, health_score: 28,
    last_email_received: daysAgo(75), total_emails_received: 3, total_emails_sent: 2,
    last_meeting: null, total_meetings: 0,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(30), twitter_interactions: 5,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c020', name: 'Fatima Al-Rashid', email: 'fatima@cloudflare.com',
    company: 'Cloudflare', role: 'Director of Engineering', tags: ['engineering', 'infrastructure'],
    relationship: 'professional', notes: 'Sharp technical leader. Working on Workers AI platform.',
    last_contact_at: daysAgo(28), days_since_contact: 28, health_score: 58,
    last_email_received: daysAgo(28), total_emails_received: 7, total_emails_sent: 5,
    last_meeting: daysAgo(35), total_meetings: 3,
    last_slack: daysAgo(30), total_slack_messages: 8,
    last_twitter_interaction: daysAgo(18), twitter_interactions: 6,
    last_linkedin_signal: daysAgo(12), linkedin_recent_signals: 'Cloudflare Workers AI hit 1M daily active users',
  },
  {
    page_id: 'c021', name: 'Kevin Hart', email: 'kevin@supabase.com',
    company: 'Supabase', role: 'Head of Growth', tags: ['growth', 'open-source'],
    relationship: 'professional', notes: 'Incredible growth hacker. Open source marketing genius.',
    last_contact_at: daysAgo(33), days_since_contact: 33, health_score: 55,
    last_email_received: daysAgo(33), total_emails_received: 6, total_emails_sent: 4,
    last_meeting: daysAgo(40), total_meetings: 2,
    last_slack: daysAgo(36), total_slack_messages: 14,
    last_twitter_interaction: daysAgo(20), twitter_interactions: 9,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c022', name: 'Isabella Romano', email: 'isabella@databricks.com',
    company: 'Databricks', role: 'ML Engineer', tags: ['ML', 'data'],
    relationship: 'acquaintance', notes: 'Met at MLSys. Working on LLM fine-tuning infrastructure.',
    last_contact_at: daysAgo(110), days_since_contact: 110, health_score: 15,
    last_email_received: daysAgo(110), total_emails_received: 2, total_emails_sent: 2,
    last_meeting: daysAgo(115), total_meetings: 1,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(85), twitter_interactions: 2,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c023', name: 'Sam Patel', email: 'sam@railway.app',
    company: 'Railway', role: 'Founder', tags: ['founder', 'infra'],
    relationship: 'close', notes: 'Building the future of deployment. Great energy, moves fast.',
    last_contact_at: daysAgo(4), days_since_contact: 4, health_score: 90,
    last_email_received: daysAgo(4), total_emails_received: 22, total_emails_sent: 19,
    last_meeting: daysAgo(8), total_meetings: 10,
    last_slack: daysAgo(4), total_slack_messages: 65,
    last_twitter_interaction: daysAgo(2), twitter_interactions: 20,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c024', name: 'Olivia Thompson', email: 'olivia@sequoia.com',
    company: 'Sequoia Capital', role: 'Principal', tags: ['investor', 'advisor'],
    relationship: 'professional', notes: 'Keen eye for developer tools market. Worth keeping warm.',
    last_contact_at: daysAgo(48), days_since_contact: 48, health_score: 42,
    last_email_received: daysAgo(48), total_emails_received: 5, total_emails_sent: 4,
    last_meeting: daysAgo(52), total_meetings: 2,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(38), twitter_interactions: 3,
    last_linkedin_signal: daysAgo(25), linkedin_recent_signals: 'Led $40M Series B in AI developer tools',
  },
  {
    page_id: 'c025', name: 'Michael Brown', email: 'michael@planetscale.com',
    company: 'PlanetScale', role: 'Senior SRE', tags: ['databases', 'reliability'],
    relationship: 'acquaintance', notes: 'MySQL expert. Helped troubleshoot our sharding issue.',
    last_contact_at: daysAgo(82), days_since_contact: 82, health_score: 25,
    last_email_received: daysAgo(82), total_emails_received: 4, total_emails_sent: 3,
    last_meeting: null, total_meetings: 0,
    last_slack: daysAgo(85), total_slack_messages: 8,
    last_twitter_interaction: null, twitter_interactions: 0,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c026', name: 'Lisa Wang', email: 'lisa@scale.com',
    company: 'Scale AI', role: 'Director of Product', tags: ['AI', 'product', 'data'],
    relationship: 'professional', notes: 'Runs data annotation products. Interested in our pipeline.',
    last_contact_at: daysAgo(19), days_since_contact: 19, health_score: 68,
    last_email_received: daysAgo(19), total_emails_received: 11, total_emails_sent: 9,
    last_meeting: daysAgo(25), total_meetings: 4,
    last_slack: daysAgo(22), total_slack_messages: 18,
    last_twitter_interaction: daysAgo(14), twitter_interactions: 5,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c027', name: 'Nathan Scott', email: 'nathan@tailscale.com',
    company: 'Tailscale', role: 'Principal Engineer', tags: ['networking', 'wireguard'],
    relationship: 'professional', notes: 'Deep networking expertise. WireGuard wizard.',
    last_contact_at: daysAgo(58), days_since_contact: 58, health_score: 35,
    last_email_received: daysAgo(58), total_emails_received: 5, total_emails_sent: 4,
    last_meeting: daysAgo(65), total_meetings: 2,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(40), twitter_interactions: 4,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c028', name: 'Hannah Lee', email: 'hannah@dagger.io',
    company: 'Dagger', role: 'DevRel Lead', tags: ['CI/CD', 'devrel'],
    relationship: 'close', notes: 'Podcast co-host for 6 episodes. Excellent storyteller.',
    last_contact_at: daysAgo(7), days_since_contact: 7, health_score: 86,
    last_email_received: daysAgo(7), total_emails_received: 21, total_emails_sent: 19,
    last_meeting: daysAgo(12), total_meetings: 8,
    last_slack: daysAgo(7), total_slack_messages: 52,
    last_twitter_interaction: daysAgo(5), twitter_interactions: 14,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c029', name: 'Roberto Diaz', email: 'roberto@temporal.io',
    company: 'Temporal', role: 'Staff Engineer', tags: ['workflows', 'distributed'],
    relationship: 'professional', notes: 'Temporal expert. Consulted on our workflow engine migration.',
    last_contact_at: daysAgo(35), days_since_contact: 35, health_score: 50,
    last_email_received: daysAgo(35), total_emails_received: 8, total_emails_sent: 6,
    last_meeting: daysAgo(40), total_meetings: 3,
    last_slack: daysAgo(38), total_slack_messages: 16,
    last_twitter_interaction: daysAgo(28), twitter_interactions: 4,
    last_linkedin_signal: daysAgo(20), linkedin_recent_signals: 'Temporal surpassed 100K workflow executions/sec milestone',
  },
  {
    page_id: 'c030', name: 'Grace Kim', email: 'grace@clerk.dev',
    company: 'Clerk', role: 'Founding Engineer', tags: ['auth', 'startup'],
    relationship: 'close', notes: 'Early Clerk team. Brilliant full-stack engineer with great taste.',
    last_contact_at: daysAgo(11), days_since_contact: 11, health_score: 80,
    last_email_received: daysAgo(11), total_emails_received: 15, total_emails_sent: 13,
    last_meeting: daysAgo(16), total_meetings: 5,
    last_slack: daysAgo(13), total_slack_messages: 36,
    last_twitter_interaction: daysAgo(8), twitter_interactions: 10,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c031', name: 'Benjamin Foster', email: 'ben@cockroachlabs.com',
    company: 'Cockroach Labs', role: 'Engineering Manager', tags: ['databases', 'distributed'],
    relationship: 'acquaintance', notes: 'CockroachDB internals expert. Mentioned at a meetup.',
    last_contact_at: daysAgo(140), days_since_contact: 140, health_score: 10,
    last_email_received: daysAgo(140), total_emails_received: 2, total_emails_sent: 1,
    last_meeting: null, total_meetings: 0,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(100), twitter_interactions: 1,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c032', name: 'Yuki Tanaka', email: 'yuki@warp.dev',
    company: 'Warp', role: 'Design Lead', tags: ['design', 'terminal', 'UX'],
    relationship: 'professional', notes: 'Redesigning the terminal experience. Great UX instincts.',
    last_contact_at: daysAgo(25), days_since_contact: 25, health_score: 62,
    last_email_received: daysAgo(25), total_emails_received: 9, total_emails_sent: 7,
    last_meeting: daysAgo(30), total_meetings: 3,
    last_slack: daysAgo(27), total_slack_messages: 14,
    last_twitter_interaction: daysAgo(18), twitter_interactions: 7,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
  {
    page_id: 'c033', name: 'Arjun Mehta', email: 'arjun@razorpay.com',
    company: 'Razorpay', role: 'VP Engineering', tags: ['fintech', 'scale'],
    relationship: 'professional', notes: 'Built Razorpay payment infra from ground up. India connection.',
    last_contact_at: daysAgo(52), days_since_contact: 52, health_score: 44,
    last_email_received: daysAgo(52), total_emails_received: 7, total_emails_sent: 5,
    last_meeting: daysAgo(60), total_meetings: 2,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(40), twitter_interactions: 3,
    last_linkedin_signal: daysAgo(15), linkedin_recent_signals: 'Razorpay processing $100B annually',
  },
  {
    page_id: 'c034', name: 'Elena Petrov', email: 'elena@jetbrains.com',
    company: 'JetBrains', role: 'Kotlin Team Lead', tags: ['kotlin', 'IDE'],
    relationship: 'acquaintance', notes: 'Met at KotlinConf. Fascinating language design philosophy.',
    last_contact_at: daysAgo(105), days_since_contact: 105, health_score: 16,
    last_email_received: daysAgo(105), total_emails_received: 3, total_emails_sent: 2,
    last_meeting: daysAgo(110), total_meetings: 1,
    last_slack: null, total_slack_messages: 0,
    last_twitter_interaction: daysAgo(70), twitter_interactions: 2,
    last_linkedin_signal: null, linkedin_recent_signals: null,
  },
]

export const mockGmailThreads: Record<string, GmailThread[]> = {
  'sarah.chen@stripe.com': [
    { thread_id: 't001', subject: 'Re: Architecture review for Q3', from_email: 'sarah.chen@stripe.com', from_name: 'Sarah Chen', snippet: 'Looks solid! A few notes on the caching layer — I think you should consider write-through instead of write-behind for...', sent_at: daysAgo(3), is_sent: false, thread_length: 4 },
    { thread_id: 't002', subject: 'StrangeLoop reunion dinner?', from_email: 'sarah.chen@stripe.com', from_name: 'Sarah Chen', snippet: 'A bunch of us are getting together in SF next month. Would love to catch up in person!', sent_at: daysAgo(10), is_sent: false, thread_length: 3 },
    { thread_id: 't003', subject: 'Intro: you + our new infra lead', from_email: 'you@youremail.com', from_name: 'You', snippet: 'Sarah, meet Alex — he just joined and I think you two would have a lot to talk about re: distributed systems...', sent_at: daysAgo(15), is_sent: true, thread_length: 2 },
  ],
  'marcus@linear.so': [
    { thread_id: 't004', subject: 'Dev tools collab ideas', from_email: 'marcus@linear.so', from_name: 'Marcus Rivera', snippet: 'Hey! Loved your tweet about developer productivity metrics. We should explore a joint blog post or...', sent_at: daysAgo(8), is_sent: false, thread_length: 5 },
    { thread_id: 't005', subject: 'Re: Linear API feedback', from_email: 'you@youremail.com', from_name: 'You', snippet: 'The new GraphQL mutations are much cleaner. One thing that would be killer is batch operations for...', sent_at: daysAgo(14), is_sent: true, thread_length: 3 },
  ],
}

export const mockCalendarEvents: CalendarEvent[] = [
  {
    event_id: 'e001', title: 'Sync with Sarah — Architecture Review',
    starts_at: new Date(now.getTime() + 2 * 3600000).toISOString(),
    ends_at: new Date(now.getTime() + 3 * 3600000).toISOString(),
    duration_mins: 60,
    attendees: [
      { email: 'sarah.chen@stripe.com', name: 'Sarah Chen', response_status: 'accepted' },
      { email: 'you@youremail.com', name: 'You', response_status: 'accepted' },
    ],
    video_link: 'https://meet.google.com/abc-defg-hij',
  },
  {
    event_id: 'e002', title: 'Coffee chat with Marcus',
    starts_at: new Date(now.getTime() + 26 * 3600000).toISOString(),
    ends_at: new Date(now.getTime() + 27 * 3600000).toISOString(),
    duration_mins: 30,
    attendees: [
      { email: 'marcus@linear.so', name: 'Marcus Rivera', response_status: 'accepted' },
    ],
    video_link: null,
  },
  {
    event_id: 'e003', title: 'Vercel partnership discussion',
    starts_at: new Date(now.getTime() + 50 * 3600000).toISOString(),
    ends_at: new Date(now.getTime() + 51 * 3600000).toISOString(),
    duration_mins: 45,
    attendees: [
      { email: 'jordan@vercel.com', name: 'Jordan Taylor', response_status: 'accepted' },
      { email: 'luis@vercel.com', name: 'Luis Garcia', response_status: 'tentative' },
    ],
    video_link: 'https://zoom.us/j/123456789',
  },
]

// Compute mock network stats from contacts array
export function getMockNetworkStats(): NetworkStats {
  const total = mockContacts.length
  const strong = mockContacts.filter(c => c.health_score >= 70).length
  const fading = mockContacts.filter(c => c.health_score >= 40 && c.health_score < 70).length
  const dormant = mockContacts.filter(c => c.health_score < 40).length
  const avg = mockContacts.reduce((sum, c) => sum + c.health_score, 0) / total

  return {
    total_contacts: total,
    strong_count: strong,
    fading_count: fading,
    dormant_count: dormant,
    avg_health_score: Math.round(avg * 10) / 10,
  }
}
